import{a as E,S as O,i}from"./assets/vendor-Cx9ob2aQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const B="https://pixabay.com/api/",M="53389241-61d9b890c2cc3baebfd2ae29c";async function f(e,r=1){const o=await E.get(B,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return{hits:o.data.hits,totalHits:o.data.totalHits}}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more-button");document.querySelector(".load-more-loader");const P=new O(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:200});function y(e){if(!e||e.length===0)return;const r=e.map(o=>{const{webformatURL:a,largeImageURL:t,tags:s,likes:n,views:w,comments:q,downloads:v}=o;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-img" src="${a}" alt="${s}" loading="lazy"/>
        </a>
        <div class="details">
          <p class="details-item"><b>Likes</b> ${n}</p>
          <p class="details-item"><b>Views</b> ${w}</p>
          <p class="details-item"><b>Comments</b> ${q}</p>
          <p class="details-item"><b>Downloads</b> ${v}</p>
        </div>
      </li>
    `}).join("");g.insertAdjacentHTML("beforeend",r),P.refresh()}function C(){g.innerHTML=""}function l(){p.classList.add("hidden")}function b(){p.classList.remove("hidden")}function L(e=h){e.classList.remove("hidden")}function S(e=h){e.classList.add("hidden")}const H=document.querySelector(".form"),R=document.querySelector("input"),$=document.querySelector(".load-more-button"),u=document.querySelector(".load-more-loader");let d="",c=1,m=0;H.addEventListener("submit",k);$.addEventListener("click",x);async function k(e){e.preventDefault();const r=R.value.trim();if(r===""){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight",closeOnClick:!0,closeOnEscape:!0});return}d=r,c=1,C(),l(),L();try{const{hits:o,totalHits:a}=await f(d,c);if(m=a,!o||o.length===0){i.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,closeOnEscape:!0});return}y(o),o.length<15||o.length===m?l():b()}catch(o){console.log("Error fetching images:",o),i.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight",closeOnClick:!0,closeOnEscape:!0})}finally{S()}}async function x(){c++,L(u),l();try{const{hits:e}=await f(d,c);y(e),e.length<15?(l(),i.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const r=document.querySelector(".gallery a");if(r){const{height:o}=r.getBoundingClientRect();scrollBy({top:o*2,behavior:"smooth"})}}catch(e){console.log(e)}finally{S(u)}}
//# sourceMappingURL=index.js.map
