import{a as v,S as E,i}from"./assets/vendor-Cx9ob2aQ.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const B="https://pixabay.com/api/",C="53389241-61d9b890c2cc3baebfd2ae29c";async function g(o,a=1){const e=await v.get(B,{params:{key:C,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}});return{hits:e.data.hits,totalHits:e.data.totalHits}}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more-button");document.querySelector(".load-more-loader");const M=new E(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:200});function h(o){if(!o||o.length===0)return;const a=o.map(e=>{const{webformatURL:s,largeImageURL:t,tags:r,likes:n,views:w,comments:q,downloads:O}=e;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-img" src="${s}" alt="${r}" loading="lazy"/>
        </a>
        <div class="details">
          <p class="details-item"><b>Likes</b> ${n}</p>
          <p class="details-item"><b>Views</b> ${w}</p>
          <p class="details-item"><b>Comments</b> ${q}</p>
          <p class="details-item"><b>Downloads</b> ${O}</p>
        </div>
      </li>
    `}).join("");f.insertAdjacentHTML("beforeend",a),M.refresh()}function P(){f.innerHTML=""}function l(){p.classList.add("hidden")}function b(){p.classList.remove("hidden")}function L(o=y){o.classList.remove("hidden")}function S(o=y){o.classList.add("hidden")}const H=document.querySelector(".form"),R=document.querySelector("input"),$=document.querySelector(".load-more-button"),m=document.querySelector(".load-more-loader");let d="",c=1,u=0;H.addEventListener("submit",k);$.addEventListener("click",A);async function k(o){o.preventDefault();const a=R.value.trim();if(a===""){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight",closeOnClick:!0,closeOnEscape:!0});return}d=a,c=1,P(),l(),L();try{const{hits:e,totalHits:s}=await g(d,c);if(u=s,!e||e.length===0){i.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",closeOnClick:!0,closeOnEscape:!0});return}h(e),e.length<15||e.length===u?l():b()}catch(e){console.log("Error fetching images:",e),i.error({title:"Error",message:"Something went wrong while fetching images. Please try again later.",position:"topRight",closeOnClick:!0,closeOnEscape:!0})}finally{S()}}async function A(){c++,L(m),l();try{const{hits:o}=await g(d,c);h(o),document.querySelectorAll(".gallery a").length>=u?(l(),i.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",closeOnClick:!0,closeOnEscape:!0})):b();const e=document.querySelector(".gallery a");if(e){const{height:s}=e.getBoundingClientRect();scrollBy({top:s*2,behavior:"smooth"})}}catch(o){console.log(o)}finally{S(m)}}
//# sourceMappingURL=index.js.map
